AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/IndentationWidth:
  EnforcedStyle: spaces
  Width: 4

Layout/LineLength:
  Max: 100

Naming/VariableName:
  EnforcedStyle: camel_case

Naming/MethodName:
  EnforcedStyle: camel_case

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
